### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by tanrax** [igrishaev/remus#9]
When I run  `parse-url`, It is printed by the terminal.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Nevertheless, it works.

**Comment by igrishaev** [comment]
@tanrax that's actually not an issue of `remus`. Looks like the ROME library requires the `slf4j` java library for logging. You may fix it by adding the following dependency in your project.clj:

```
[org.slf4j/slf4j-api "1.7.30"]
```

This kind of message appears quite often when you use native Java libraries.

**Comment by tanrax** [comment]
Thank you for your response. Unfortunately the error keeps occurring, am I the only one with this problem?

**Comment by igrishaev** [comment]
@tanrax the dependency I shared before was incomplete. Here are the links with full information:

- https://www.programmersought.com/article/14935599897/
- https://www.bahmanm.com/2014/12/clojure-project-add-logging.html

**Comment by tanrax** [comment]
I've got it fixed.

A file called log4j.properties must be created in src. It should have the following content.

```
log4j.rootLogger=DEBUG, R
#Output to the file, and a new file is generated when the file size reaches the specified size
log4j.appender.R=org.apache.log4j.RollingFileAppender
#Output to the console
#log4j.appender.stdout=org.apache.log4j.ConsoleAppender
#log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.R.File=./log/logger1.log

log4j.appender.R.MaxBackupIndex=20

log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=[%d][%p][%c] %m%n
```

And add the following dependency.

```
  [org.slf4j/slf4j-log4j12 "1.7.25"]
  [log4j/log4j "1.2.12" :exclusions [javax.mail/mail
                                                    javax.jms/jms
                                                    com.sun.jmdk/jmxtools
                                                    com.sun.jmx/jmxri]]
```

**Comment by igrishaev** [comment]
The better place for this file would be `resources`, imo. Src is usually for the code source files but not configs.
